Sourcing minigraphs...
Traceback (most recent call last):
Traceback (most recent call last):
  File "/mnt/ufs18/home-245/martjor/repos/dev_pt/batch/../src/miniaturize.py", line 63, in <module>
Traceback (most recent call last):
  File "/mnt/ufs18/home-245/martjor/repos/dev_pt/batch/../src/miniaturize.py", line 63, in <module>
Traceback (most recent call last):
  File "/mnt/ufs18/home-245/martjor/repos/dev_pt/batch/../src/miniaturize.py", line 63, in <module>
Traceback (most recent call last):
  File "/mnt/ufs18/home-245/martjor/repos/dev_pt/batch/../src/miniaturize.py", line 63, in <module>
  File "/mnt/ufs18/home-245/martjor/repos/dev_pt/batch/../src/miniaturize.py", line 63, in <module>
Traceback (most recent call last):
  File "/mnt/ufs18/home-245/martjor/repos/dev_pt/batch/../src/miniaturize.py", line 63, in <module>
        beta_opt = params['beta']    beta_opt = params['beta']
               ~~~~~~^^^^^^^^
KeyError: 'beta'
beta_opt = params['beta']
               ~~~~~~^^^^^^^^
KeyError: 'beta'

               ~~~~~~^^^^^^^^
KeyError: 'beta'
    beta_opt = params['beta']
               ~~~~~~^^^^^^^^
KeyError: 'beta'
    beta_opt = params['beta']
               ~~~~~~^^^^^^^^
KeyError: 'beta'
    beta_opt = params['beta']
               ~~~~~~^^^^^^^^
KeyError: 'beta'
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpiexec detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[5113,1],5]
  Exit code:    1
--------------------------------------------------------------------------
